# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAJOR',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('mjr_num', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('std_num', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.MAJOR')),
            ],
        ),
    ]
