# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20171129_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('minit', models.CharField(max_length=3)),
                ('lname', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bdate', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('salary', models.IntegerField()),
                ('dno', models.CharField(max_length=1)),
                ('super_ssn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_app.EMPLOYEE')),
            ],
        ),
    ]
