# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEPT_LOCATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlocation', models.CharField(max_length=20)),
                ('dnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_app.DEPARTMENT')),
            ],
        ),
    ]
